// Bounded co-author helpers. These propose semantic Name source; they never mutate canonical project state.
const clean=s=>String(s||'').trim();
function sentences(story){return clean(story).split(/(?<=[。！？!?])\s*|\n+/).map(clean).filter(Boolean);}
function purposeFor(s,i,count){if(i===0&&/場所|広場|部屋|街|朝|夜|arrive|enter|establish/i.test(s))return'establish';if(/殴|斬|攻撃|衝突|爆発|走|飛|attack|slash|impact/i.test(s))return'impact';if(/驚|振り向|反応|息|沈黙|reaction/i.test(s))return'reaction';if(/現れ|判明|正体|開く|reveal/i.test(s))return'reveal';if(i===count-1)return'climax';return'story';}
function importanceFor(p){return /climax/.test(p)?'high':/impact|reveal/.test(p)?'0.8':/establish/.test(p)?'0.55':'medium';}
function holdFor(p){return /reaction|reveal/.test(p)?'0.7':/impact/.test(p)?'0.3':/climax/.test(p)?'0.6':'0.5';}
export function proposeNameFromStory(story,{title='AI Co-authored Page'}={}){const beats=sentences(story).slice(0,8);if(!beats.length)throw new Error('Story text is empty.');const lines=[`# Page 1: ${title}`,'@layout: auto',''];beats.forEach((s,i)=>{const purpose=purposeFor(s,i,beats.length);lines.push(`コマ${i+1}: ${s}`,`目的: ${purpose}`,`重要度: ${importanceFor(purpose)}`,`間: ${holdFor(purpose)}`);if(/impact/.test(purpose))lines.push('動き方向: down-left','注目: action.contact');if(/reveal/.test(purpose))lines.push('注目: reveal.subject');lines.push('');});return lines.join('\n');}
export function patchPanelSemantics(nameSource,panelNumber,patch={}){const lines=String(nameSource).split(/\r?\n/);let active=false,found=false;const out=[];for(const line of lines){const m=line.trim().match(/^(?:panel|p|コマ)\s*(\d+)\s*[:：-]/i);if(m){if(active)for(const [k,v]of Object.entries(patch))out.push(`${k}: ${v}`);active=Number(m[1])===Number(panelNumber);found ||= active;}out.push(line);}if(active)for(const [k,v]of Object.entries(patch))out.push(`${k}: ${v}`);if(!found)throw new Error(`Panel ${panelNumber} not found.`);return out.join('\n');}
export function lockPanelFromProject(nameSource,project,pageIndex,panelIndex){const p=project.pages?.[pageIndex]?.panels?.[panelIndex];if(!p)throw new Error('Panel not found.');const r=p.rect;return patchPanelSemantics(nameSource,panelIndex+1,{'コマ固定':`${r.x}, ${r.y}, ${r.w}, ${r.h}`});}
