const q=(v)=>JSON.stringify(String(v));
export function buildExecutablePrompt(project,pageIndex=0){
  const page=project.pages[pageIndex],text=page.panels.flatMap(p=>[...p.balloons.map(b=>b.text),...(p.effects.sfxText?[p.effects.sfxText]:[])]),rtl=project.meta.readingDirection!=='ltr',hasMobs=page.panels.some(p=>p.characters.some(c=>c.characterRole==='mob'||c.renderDetail==='simplified'));
  const lines=['# Executable Manga Generation Brief',`Work: ${project.meta.title}`,`Page: P${String(page.pageNumber).padStart(3,'0')}`,`Reading: ${project.meta.readingDirection}`,`READING ORDER: ${rtl?'right-to-left, then top-to-bottom':'left-to-right, then top-to-bottom'}`,'','## INPUT AUTHORITY','- Pxxx.clean.svg/png is the spatial composition contract.','- work.manga.json is the semantic authority.','- Preserve panel geometry, character placement, solved pose silhouette, weapon/contact location and reading flow.',`- Preserve canonical panel sequence for ${rtl?'Japanese RTL manga. Do not mirror or reinterpret it as left-to-right.':'LTR reading. Do not mirror or reverse it.'}`,'- Do not reproduce labels from the annotated blueprint.',...(hasMobs?['- Characters marked role=mob / detail=simplified are low-information background figures: prioritize silhouette, pose, hairstyle/clothing block shapes; omit detailed eyes, nose and mouth unless a specific beat requires them; never let mob facial detail compete with main characters.']:[]),'','## TEXT TO RENDER',...(text.length?text.map(t=>`- ${q(t)}`):['- (none)']),''];
  for(const p of page.panels){
    lines.push(`## Panel ${p.order}`,`ACTION: ${p.actionIntent}`,`CAMERA: ${p.camera.distance}, ${p.camera.angle}, ${p.camera.viewpoint}`,`BACKGROUND: ${p.background.location||'(unspecified)'} ${p.background.timeOfDay||''}`.trim(),`ENERGY: ${Number(p.importance?.energy??.5).toFixed(2)}`);
    if(p.attention?.primary)lines.push(`PRIMARY ATTENTION: ${p.attention.primary}`);
    if(p.flow?.entry||p.flow?.exit)lines.push(`READING FLOW: ${p.flow?.entry||'auto'} -> ${p.flow?.exit||'auto'}`);const frame=[];if(p.shape?.preset)frame.push(`shape=${p.shape.preset}`);if(p.inset?.kind)frame.push(`inset=${p.inset.kind}:${p.inset.anchor||'auto'}:${p.inset.size||'auto'}`);if(p.style?.bleed&&p.style.bleed!=='none')frame.push(`bleed=${p.style.bleed}`);if(p.style?.breakout&&p.style.breakout!=='none')frame.push(`breakout=${p.style.breakout}`);if(frame.length)lines.push(`FRAME DIRECTION: ${frame.join('; ')}`);
    lines.push(`CAST: ${p.characters.map(c=>`${c.name} [role=${c.characterRole||'main'}; detail=${c.renderDetail||'standard'}; pose=${c.poseId}; expression=${c.expression.type}; gaze=${c.gaze?.target||'auto'}; support=${c.supportState}; motion=${c.motionPhase}; depth=${c.depthOrder??0}]`).join(', ')||'(none)'}`);
    for(const x of p.interactions||[])lines.push(`CONTACT: ${x.intent||`${x.source?.character}.${x.source?.part} > ${x.target?.character}.${x.target?.part}`}`);
    lines.push(`EFFECT: ${p.effects.lineEffect}${p.effects.sfxText?`; SFX ${q(p.effects.sfxText)}`:''}`,'');
  }
  return lines.join('\n');
}
