// Manga-expression pass layered over the canonical Blueprint Engine.
// AI authors semantic intent; this pass resolves it into deterministic geometry/state.
import { compileName } from './blueprint-engine.mjs';
import { solveLayout } from './layout-solver.mjs';
import { solveProjectPoses } from './pose-contact-solver.mjs';

const split = (v='') => v.split(/[,、]/).map(x=>x.trim()).filter(Boolean);
const clamp01 = (n) => Math.max(0, Math.min(1, Number.isFinite(n) ? n : 0));
const weight = (v='', fallback=.5) => {const s=String(v).trim().toLowerCase();const n=Number(s);if(Number.isFinite(n))return clamp01(n);if(/climax|maximum|最高|決め|最大/.test(s))return 1;if(/high|strong|重要|強/.test(s))return .8;if(/medium|normal|中|普通/.test(s))return .5;if(/low|weak|低|弱/.test(s))return .25;return fallback;};
function parseImportance(value=''){const out={narrative:.5,visual:.5,transition:.5};for(const part of split(value)){const m=part.match(/^(narrative|story|物語|visual|絵|視覚|transition|遷移|つなぎ)\s*[=：:]\s*(.+)$/i);if(!m){const w=weight(part,.5);out.narrative=w;out.visual=w;continue;}if(/narrative|story|物語/i.test(m[1]))out.narrative=weight(m[2]);else if(/visual|絵|視覚/i.test(m[1]))out.visual=weight(m[2]);else out.transition=weight(m[2]);}return out;}
function parseSemanticPanels(text){const pages=[];let page={layout:'auto',panels:[]};let panel=null;const flushPage=()=>{if(page.panels.length)pages.push(page);page={layout:'auto',panels:[]};panel=null;};for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(/^#{1,3}\s*(?:page|p|ページ)\b/i.test(line)){flushPage();continue;}const ld=line.match(/^@layout\s*[:：]\s*(.+)$/i);if(ld){page.layout=ld[1].trim();continue;}const pm=line.match(/^(?:[-*]\s*)?(?:panel|p|コマ)\s*\d+\s*[:：-]/i);if(pm){panel={shape:'rectangle',size:'auto',inset:'',pose:{},gaze:{},depth:{},support:{},motion:{},contacts:[],importance:{narrative:.5,visual:.5,transition:.5},timing:{hold:.5},attention:{primary:'',secondary:''},flow:{entry:'',exit:''}};page.panels.push(panel);continue;}if(!panel)continue;const field=(names)=>line.match(new RegExp(`^(?:${names})\\s*[:：]\\s*(.+)$`,'i'))?.[1]?.trim();let v;if((v=field('shape|境界|コマ形')))panel.shape=v;else if((v=field('size|コマサイズ')))panel.size=v;else if((v=field('inset|インセット')))panel.inset=v;else if((v=field('importance|重要度')))panel.importance=parseImportance(v);else if((v=field('hold|間|滞留')))panel.timing.hold=weight(v);else if((v=field('primary attention|primary|注目|主注目')))panel.attention.primary=v;else if((v=field('secondary attention|secondary|副注目')))panel.attention.secondary=v;else if((v=field('entry|視線入口')))panel.flow.entry=v;else if((v=field('exit|視線出口')))panel.flow.exit=v;else if((v=field('pose|ポーズ')))assignMap(panel.pose,v);else if((v=field('gaze|視線')))assignMap(panel.gaze,v);else if((v=field('depth|前後|奥行')))assignMap(panel.depth,v);else if((v=field('support|支持')))assignMap(panel.support,v);else if((v=field('motion|動作段階')))assignMap(panel.motion,v);else if((v=field('contact|接触')))panel.contacts.push(...split(v));else if((v=field('強調'))){const w=weight(v);panel.importance.visual=Math.max(panel.importance.visual,w);panel.importance.narrative=Math.max(panel.importance.narrative,w*.85);}}if(page.panels.length)pages.push(page);return pages;}
function assignMap(target,value){const m=value.match(/^([^>＞]+)[>＞]\s*(.+)$/);if(m)target[m[1].trim()]=m[2].trim();}
function quad(rect,preset){const {x,y,w,h}=rect,d=Math.min(w,h)*.10;const pts={'diagonal-left':[{x:x+d,y},{x:x+w,y},{x:x+w-d,y:y+h},{x,y:y+h}],'diagonal-right':[{x,y},{x:x+w-d,y},{x:x+w,y:y+h},{x:x+d,y:y+h}],'trapezoid-left':[{x:x+d,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}],'trapezoid-right':[{x,y},{x:x+w-d,y},{x:x+w,y:y+h},{x,y:y+h}]};return {kind:'quad',preset,points:pts[preset]||[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}]};}
function normalizeShape(v=''){if(/diagonal[- ]?left|斜め左/i.test(v))return'diagonal-left';if(/diagonal[- ]?right|斜め右|斜め/i.test(v))return'diagonal-right';if(/trapezoid[- ]?left|台形左/i.test(v))return'trapezoid-left';if(/trapezoid[- ]?right|台形右|台形/i.test(v))return'trapezoid-right';return'rectangle';}
function support(v=''){return/air|空中|jump/i.test(v)?'airborne':/supported|寄りかか|支え/i.test(v)?'supported':/unknown|不明/i.test(v)?'unknown':'grounded';}
function motion(v=''){for(const [re,val] of [[/anticip|予備/,'anticipation'],[/approach|接近/,'approach'],[/launch|踏み切/,'launch'],[/air|空中/,'airborne'],[/impact|衝突|着地/,'impact'],[/recover|回復/,'recovery']])if(re.test(v))return val;return'still';}
function depthRank(v=''){return/foreground|最前|手前/i.test(v)?2:/background|奥/i.test(v)?-2:/front|前/i.test(v)?1:/back|後/i.test(v)?-1:0;}
function energy(imp,hold=.5){return clamp01(imp.narrative*.42+imp.visual*.43+imp.transition*.15+Math.max(0,hold-.5)*.10);}
function annotateEnergy(sp){const scores=sp.panels.map(s=>energy(s.importance,s.timing.hold));sp.panels.forEach((s,i)=>{const score=scores[i]??.5,prev=i?scores[i-1]:score;s.importance={...s.importance,energy:score,emphasisDelta:score-prev};});}
function applySolvedGeometry(page,sp,readingDirection){annotateEnergy(sp);const solved=solveLayout(sp.panels,{hint:sp.layout,readingDirection});page.layoutDecision={solver:'candidate-v1',winner:solved.name,score:solved.score,candidates:solved.candidates};page.panels.forEach((panel,i)=>{const solvedRect=solved.rects[i];if(solvedRect){panel.rect={x:solvedRect.x,y:solvedRect.y,w:solvedRect.w,h:solvedRect.h};if(solvedRect.skew&&!(sp.panels[i]?.shape&&sp.panels[i].shape!=='rectangle'))sp.panels[i].shape=solvedRect.skew;}const s=sp.panels[i];panel.importance={...s.importance};panel.timing={...s.timing};panel.attention={...s.attention};panel.flow={...s.flow};});}

export function compileMangaName(text,options={}){const project=compileName(text,options);const semantic=parseSemanticPanels(text);project.pages.forEach((page,pi)=>{const sp=semantic[pi]||{layout:'auto',panels:[]};applySolvedGeometry(page,sp,project.meta.readingDirection);page.panels.forEach((panel,i)=>{const s=sp.panels[i]||{};const preset=normalizeShape(s.shape);if(preset!=='rectangle')panel.shape=quad(panel.rect,preset);if(s.inset){const m=s.inset.match(/(?:parent|親)?\s*(?:panel|p|コマ)?\s*(\d+)/i);const parentIndex=m?Number(m[1])-1:Math.max(0,i-1);const parent=page.panels[parentIndex];if(parent&&parent!==panel){const anchor=/top-left|左上/i.test(s.inset)?'top-left':/bottom-left|左下/i.test(s.inset)?'bottom-left':/bottom-right|右下/i.test(s.inset)?'bottom-right':/center|中央/i.test(s.inset)?'center':'top-right';const size=/large|大/i.test(s.inset)?'large':/small|小/i.test(s.inset)?'small':'medium';panel.inset={kind:'panel-in-panel',parentPanelId:parent.id,anchor,size};panel.style.border='inset';const ratio=size==='small'?.28:size==='large'?.52:.40,iw=parent.rect.w*ratio,ih=parent.rect.h*ratio;const left=/left/.test(anchor),bottom=/bottom/.test(anchor);panel.rect={x:left?parent.rect.x+18:parent.rect.x+parent.rect.w-iw-18,y:bottom?parent.rect.y+parent.rect.h-ih-18:parent.rect.y+18,w:iw,h:ih};if(anchor==='center'){panel.rect.x=parent.rect.x+(parent.rect.w-iw)/2;panel.rect.y=parent.rect.y+(parent.rect.h-ih)/2;}panel.shape=quad(panel.rect,preset);}}panel.characters.forEach(c=>{c.poseId=s.pose?.[c.name]||c.poseId;c.gaze.target=s.gaze?.[c.name]||c.gaze.target;c.supportState=support(s.support?.[c.name]||'');c.motionPhase=motion(s.motion?.[c.name]||'');c.depthOrder=depthRank(s.depth?.[c.name]||'');});panel.characters.sort((a,b)=>(a.depthOrder||0)-(b.depthOrder||0));panel.interactions=(s.contacts||[]).map(raw=>{const m=raw.match(/^([\w.-]+)\.([\w-]+)\s*[>＞]\s*([\w.-]+)\.([\w-]+)$/);return m?{type:'contact',source:{character:m[1],part:m[2]},target:{character:m[3],part:m[4]},intent:raw}:{type:'contact',intent:raw};});});});solveProjectPoses(project);project.meta.compiler={name:'manga-expression-grammar',version:4,source:'AI Name DSL',poseSolver:'deterministic-2d-contact-v1'};return project;}
export { parseSemanticPanels };
