import{buildLayoutRecipe,listLayoutRecipes,layoutRecipeCount,layoutSettingsSnippet}from'../../core/layout-recipes.mjs';import'./layout-catalog.css';
const byId=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const panelCount=byId<HTMLSelectElement>('panelCount'),seed=byId<HTMLInputElement>('seed'),mutation=byId<HTMLInputElement>('mutation'),mutationOut=byId<HTMLOutputElement>('mutationOut'),grid=byId<HTMLElement>('catalogGrid'),summary=byId<HTMLElement>('summary');
const params=new URLSearchParams(location.search);panelCount.value=params.get('panels')||'4';seed.value=params.get('seed')||'0';mutation.value=params.get('mutation')||'.20';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
async function copy(text:string){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const a=document.createElement('textarea');a.value=text;document.body.append(a);a.select();document.execCommand('copy');a.remove();}
function preview(rects:Array<{x:number;y:number;w:number;h:number}>){const W=600,H=848;return `<svg viewBox="0 0 1200 1697" aria-hidden="true"><rect width="1200" height="1697" fill="#fff"/>${rects.map((r,i)=>`<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" rx="8" fill="#f8fafc" stroke="#111827" stroke-width="10"/><text x="${r.x+r.w/2}" y="${r.y+r.h/2}" text-anchor="middle" dominant-baseline="middle" font-family="sans-serif" font-weight="700" font-size="44" fill="#64748b">P${i+1}</text>`).join('')}</svg>`;}
function currentQuery(recipeId?:string){const q=new URLSearchParams({panels:panelCount.value,seed:seed.value,mutation:Number(mutation.value).toFixed(2)});if(recipeId)q.set('recipe',recipeId);return q;}
function render(){
 const count=Number(panelCount.value),m=Number(mutation.value)||0,recipes=listLayoutRecipes({panelCount:count}),selected=params.get('recipe');mutationOut.value=m.toFixed(2);summary.textContent=`${recipes.length} recipes / ${count}コマ（Recipe Bank全体 ${layoutRecipeCount()} base combinations）`;
 grid.innerHTML=recipes.map((recipe:any)=>{const built=buildLayoutRecipe(recipe.id,{width:1200,height:1697,panelCount:count,seed:seed.value,mutation:m});const snippet=layoutSettingsSnippet({recipeId:recipe.id,panelCount:count,seed:seed.value,mutation:m});const editorQ=new URLSearchParams({layoutRecipe:recipe.id,layoutPanels:String(count),layoutSeed:seed.value,layoutMutation:m.toFixed(2)});return `<article class="recipe-card ${selected===recipe.id?'selected':''}" data-recipe="${esc(recipe.id)}"><div class="recipe-preview">${preview(built.rects)}</div><div class="recipe-body"><div class="recipe-heading"><h2>${esc(recipe.ja)}</h2><code>${esc(recipe.id)}</code></div><p>${esc(recipe.helpJa)}</p><div class="tags">${recipe.tags.map((t:string)=>`<span>${esc(t)}</span>`).join('')}</div><pre>${esc(snippet)}</pre><div class="recipe-actions"><button type="button" data-copy="${esc(recipe.id)}">設定をコピー</button><a href="./editor.html?${editorQ}">Editorで使う</a></div></div></article>`;}).join('');
 const q=currentQuery();history.replaceState(null,'',`?${q}`);
}
grid.addEventListener('click',async event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button[data-copy]');if(!button)return;const id=button.dataset.copy!,count=Number(panelCount.value),m=Number(mutation.value)||0;await copy(layoutSettingsSnippet({recipeId:id,panelCount:count,seed:seed.value,mutation:m})+`\n# CLI: --layout ${id} --seed ${seed.value} --mutation ${m.toFixed(2)}`);button.textContent='コピー済み';setTimeout(()=>button.textContent='設定をコピー',900);});
panelCount.addEventListener('change',render);seed.addEventListener('input',render);mutation.addEventListener('input',render);byId<HTMLButtonElement>('reroll').addEventListener('click',()=>{seed.value=String(Math.floor(Math.random()*1_000_000));render();});byId<HTMLButtonElement>('copyUrl').addEventListener('click',()=>copy(location.href));render();